ktor {
    deployment {
        host = "0.0.0.0"
        port = 8080
    }

    application {
        modules = [ru.school21.tictactoe.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/tictactoe"
    user = "postgres"
    password = "ruslan"
}